### ISSUE TITLE
Intellij 12 support

### ISSUE THREAD

**Issue by sytolk** [shyiko/native2asciiplug#1]
I have use this plugin with intellij 11 but when I migrate to INtellij IDEA 12 this plugin don`t convert my UTF-8 properties files to native characters.

**Comment by shyiko** [comment]
Thanks for reporting.

Seems like Intellij IDEA now comes with "Settings -> Compiler -> Use external build" turned on by default. Simple switching it off returns things back to normal.

I'm leaving issue open as a reminder for external build support.
