### ISSUE TITLE
plugin fail with new Intellij 13.1.3 build

### ISSUE THREAD

**Issue by sytolk** [shyiko/native2asciiplug#3]
Plugin works with Intellij 13.1.2 but after update to last Intellij version 13.1.3 stop working.

**Comment by sytolk** [comment]
Quick fix you can compile project with maven and use:

```
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>native2ascii-maven-plugin</artifactId>
                <version>1.0-beta-1</version>
                <executions>
                    <execution>
                        <id>native2ascii-utf8</id>
                        <goals>
                            <goal>native2ascii</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
```

**Comment by shyiko** [comment]
Please re-check your configuration. Just tried it on 13.1.3. Everything works as expected.

**Comment by sytolk** [comment]
On Intellij 13.1.3 version PHP plugin failed to load. I have disable PHP plugin and re-check and its works now.. maybe Intellij not load native2ascii plugin if PHP plugin failed.
Thanks!

**Comment by sytolk** [comment]
In Intellij 13.1.3 native2ascii work after Clean artifacts, Make project and run its ok. After that if I run Rebuild Project -> property files in war artifact don`t have native-encoded characters.
